# Generated by Django 4.1.3 on 2022-11-30 14:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('fullname', models.CharField(max_length=50, null=True)),
                ('phone', models.IntegerField(null=True)),
                ('company_name', models.CharField(max_length=150, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('address', models.CharField(max_length=150, null=True)),
                ('company_url', models.CharField(max_length=100, null=True)),
                ('Typeofincubation', models.CharField(max_length=50, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Declinded', 'Declined'), ('Approved', 'Approved')], default='Pending', max_length=50, null=True)),
                ('alloted', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_available', models.BooleanField(default=True)),
                ('reversed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userapi.applicationform')),
            ],
        ),
        migrations.CreateModel(
            name='AllUserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
